sudo: required
services:
 - docker

before_install:
 - docker build -t greendevops/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true greendevops/react-test npm test

after_success:
 - docker build -t greendevops/multi-client ./client
 - docker build -t greendevops/multi-nginx ./nginx
 - docker build -t greendevops/multi-server ./server
 - docker build -t greendevops/multi-worker ./worker

 - docker login -u "DOCKER_ID" -p "$DOCKER_PASSWORD"
 - docker push greendevops/multi-client greendevops/multi-nginx greendevops/multi-server greendevops/multi-worker