sudo: required
services:
 - docker

before_install:
 - docker build -t greendevops/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true greendevops/react-test npm test

after_success:
 - docker build -t greendevops/multi-client ./client
 - docker build -t greendevops/multi-nginx ./nginx
 - docker build -t greendevops/multi-server ./server
 - docker build -t greendevops/multi-worker ./worker

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push greendevops/multi-client
 - docker push greendevops/multi-nginx
 - docker push greendevops/multi-server
 - docker push greendevops/multi-worker
